# Make sure to check the documentation at http://goreleaser.com
builds:
- skip: true
archives:
- format: binary
source:
  enabled: false
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
